version: "3.8"

name: brainspread

volumes:
  brainspread_postgres:
    external: true

services:
  db:
    image: postgres:15.4
    env_file:
      - ./.env
    environment:
      - PGPORT=${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - brainspread_postgres:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - STATIC_ROOT=/code/app/static/
      - MEDIA_ROOT=/code/app/media/
    command:
      - "/code/bin/wait-for-it.sh"
      - "db:${POSTGRES_PORT:-5432}"
      - "--"
      - "python"
      - "/code/app/manage.py"
      - "runserver"
      - "0.0.0.0:${WEB_PORT:-8000}"
    volumes:
      - .:/code
    ports:
      - "${WEB_PORT:-8000}:${WEB_PORT:-8000}"
    depends_on:
      - db
