# Generated by Django 5.0.2 on 2025-06-17 21:01

import uuid
from django.db import migrations, models


def generate_uuid_for_existing_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250617_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(generate_uuid_for_existing_users),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
