# Generated by Django 5.0.2 on 2025-06-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone (e.g., America/New_York, UTC, etc.)", max_length=50, verbose_name='timezone'),
        ),
    ]
