# Generated by Django 5.0.2 on 2025-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="dark",
                help_text="User's preferred theme (dark or light)",
                max_length=10,
                verbose_name="theme",
            ),
        ),
    ]
