# Generated by Django 5.0.2 on 2025-07-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("solarized_dark", "Solarized Dark"),
                    ("solarized_light", "Solarized Light"),
                    ("monokai", "Monokai"),
                    ("earthy", "Earthy"),
                ],
                default="dark",
                help_text="User's preferred theme",
                max_length=20,
                verbose_name="theme",
            ),
        ),
    ]
