# Generated by Django 5.0.2 on 2025-06-18 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_block_blockproperty_blockreference_dailynote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailynote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailynote',
            name='page',
        ),
        migrations.RemoveField(
            model_name='dailynote',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='pages_user_id_38e19f_idx',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_daily_note',
        ),
        migrations.AddField(
            model_name='block',
            name='collapsed',
            field=models.BooleanField(default=False, help_text='Whether block is collapsed'),
        ),
        migrations.AddField(
            model_name='block',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('embed', 'Embed'), ('code', 'Code'), ('quote', 'Quote')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='blocks/'),
        ),
        migrations.AddField(
            model_name='block',
            name='media_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata for media files'),
        ),
        migrations.AddField(
            model_name='block',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL for media content'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='migrated_to_blocks',
            field=models.BooleanField(default=False, help_text='Whether this entry has been migrated to blocks'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('page', 'Regular Page'), ('daily', 'Daily Note'), ('template', 'Template')], default='page', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('bullet', 'Bullet Point'), ('todo', 'Todo'), ('done', 'Done'), ('heading', 'Heading'), ('quote', 'Quote'), ('code', 'Code Block'), ('divider', 'Divider')], default='bullet', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, help_text='Text content of the block'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['content_type'], name='blocks_content_f656d7_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_type'], name='blocks_block_t_a60150_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['user', 'page_type', 'date'], name='pages_user_id_c2db26_idx'),
        ),
        migrations.DeleteModel(
            name='DailyNote',
        ),
    ]
