# Generated by Django 5.0.2 on 2025-06-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_block_properties_delete_blockproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
