# Generated by Django 5.0.2 on 2025-06-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_remove_journal_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text='Text content of the page'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether the page is published'),
        ),
    ]
