# Generated by Django 5.0.2 on 2025-07-03 22:29

from django.db import migrations, models


def complete_tag_to_page_migration(apps, schema_editor):
    """
    Complete the migration by adding blocks to tag pages
    """
    # This migration originally completed the migration from the old tagging system
    # Since we've removed the tagging app, this is now a no-op
    pass


def reverse_complete_tag_to_page_migration(apps, schema_editor):
    """
    Reverse the completion of migration
    """
    # Clear all M2M relationships for tag pages
    Page = apps.get_model('knowledge', 'Page')
    Block = apps.get_model('knowledge', 'Block')
    
    for tag_page in Page.objects.filter(page_type='tag'):
        for block in Block.objects.filter(pages=tag_page):
            block.pages.remove(tag_page)


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_auto_20250703_2228"),
    ]

    operations = [
        # Complete the data migration
        migrations.RunPython(
            complete_tag_to_page_migration,
            reverse_complete_tag_to_page_migration,
        ),
    ]
