# Generated by Django 5.0.2 on 2025-07-03 22:29

from django.db import migrations, models


def complete_tag_to_page_migration(apps, schema_editor):
    """
    Complete the migration by adding blocks to tag pages
    """
    Tag = apps.get_model('tagging', 'Tag')
    TaggedItem = apps.get_model('tagging', 'TaggedItem')
    Page = apps.get_model('knowledge', 'Page')
    Block = apps.get_model('knowledge', 'Block')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        block_content_type = ContentType.objects.get(app_label='knowledge', model='block')
    except ContentType.DoesNotExist:
        return
    
    # Now that the M2M field exists, we can create the relationships
    for tag in Tag.objects.all():
        try:
            tag_page = Page.objects.get(title=f"#{tag.name}", page_type='tag')
            
            # Find all blocks tagged with this tag
            tagged_blocks = TaggedItem.objects.filter(
                tag=tag,
                content_type=block_content_type
            )
            
            # Add each tagged block to the tag page
            for tagged_item in tagged_blocks:
                try:
                    block = Block.objects.get(pk=tagged_item.object_id)
                    # Add the block to the tag page using the new many-to-many relationship
                    block.pages.add(tag_page)
                except Block.DoesNotExist:
                    continue
        except Page.DoesNotExist:
            continue


def reverse_complete_tag_to_page_migration(apps, schema_editor):
    """
    Reverse the completion of migration
    """
    # Clear all M2M relationships for tag pages
    Page = apps.get_model('knowledge', 'Page')
    Block = apps.get_model('knowledge', 'Block')
    
    for tag_page in Page.objects.filter(page_type='tag'):
        for block in Block.objects.filter(pages=tag_page):
            block.pages.remove(tag_page)


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_auto_20250703_2228"),
    ]

    operations = [
        # Complete the data migration
        migrations.RunPython(
            complete_tag_to_page_migration,
            reverse_complete_tag_to_page_migration,
        ),
    ]
