# Generated by Django 5.0.2 on 2025-07-04 02:58

from django.db import migrations
import re


def update_page_titles_to_tag_format(apps, schema_editor):
    """Convert all existing page titles to tag format"""
    Page = apps.get_model('knowledge', 'Page')
    
    for page in Page.objects.all():
        original_title = page.title
        
        # Skip if already in tag format
        if original_title.startswith('#'):
            continue
            
        # Convert title to tag format
        # Replace spaces and special characters with hyphens, convert to lowercase
        tag_title = re.sub(r'[^\w\s-]', '', original_title)  # Remove special chars except hyphens
        tag_title = re.sub(r'\s+', '-', tag_title)  # Replace spaces with hyphens
        tag_title = tag_title.lower().strip('-')  # Lowercase and strip leading/trailing hyphens
        
        # Add hashtag prefix
        tag_title = f"#{tag_title}"
        
        # Update the page
        page.title = tag_title
        page.save(update_fields=['title'])
        
        print(f"Updated page title: '{original_title}' -> '{tag_title}'")


def reverse_page_titles_from_tag_format(apps, schema_editor):
    """Reverse the tag format conversion (remove # prefix and convert hyphens to spaces)"""
    Page = apps.get_model('knowledge', 'Page')
    
    for page in Page.objects.all():
        if page.title.startswith('#'):
            # Remove hashtag and convert back
            original_title = page.title[1:]  # Remove #
            original_title = original_title.replace('-', ' ')  # Replace hyphens with spaces
            original_title = original_title.title()  # Title case
            
            page.title = original_title
            page.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0008_auto_20250703_2229"),
    ]

    operations = [
        migrations.RunPython(
            update_page_titles_to_tag_format,
            reverse_page_titles_from_tag_format
        ),
    ]
