# Generated by Django 5.0.2 on 2025-07-04 03:01

from django.db import migrations, models


def populate_title_as_tag(apps, schema_editor):
    """Populate title_as_tag field for existing pages"""
    Page = apps.get_model('knowledge', 'Page')
    
    for page in Page.objects.all():
        # Since pages already have hashtag format from previous migration,
        # we need to convert them back to human readable and set title_as_tag
        if page.title.startswith('#'):
            # Extract tag format for title_as_tag
            page.title_as_tag = page.title
            
            # Convert title to human readable
            human_title = page.title[1:]  # Remove #
            human_title = human_title.replace('-', ' ')  # Replace hyphens with spaces
            human_title = human_title.title()  # Title case
            page.title = human_title
        else:
            # Generate tag format from current title
            import re
            tag_title = re.sub(r'[^\w\s-]', '', page.title)
            tag_title = re.sub(r'\s+', '-', tag_title)
            tag_title = tag_title.lower().strip('-')
            page.title_as_tag = f"#{tag_title}"
        
        page.save(update_fields=['title', 'title_as_tag'])


def reverse_title_as_tag(apps, schema_editor):
    """Reverse the title_as_tag population"""
    Page = apps.get_model('knowledge', 'Page')
    
    for page in Page.objects.all():
        if page.title_as_tag:
            # Set title back to tag format
            page.title = page.title_as_tag
            page.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0009_auto_20250704_0258"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="title_as_tag",
            field=models.CharField(
                blank=True,
                help_text="Hashtag format for linking (auto-generated from title)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                help_text="Human-readable page title", max_length=200
            ),
        ),
        migrations.RunPython(
            populate_title_as_tag,
            reverse_title_as_tag
        ),
    ]
