# Generated by Django 5.0.2 on 2025-07-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0010_add_title_as_tag_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="title_as_tag",
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(help_text="URL-friendly identifier", max_length=200),
        ),
    ]
