# Generated by Django 5.0.2 on 2025-07-04 03:08

from django.db import migrations


def convert_tag_pages_to_regular(apps, schema_editor):
    """Convert all tag pages to regular pages since we no longer use page_type=tag"""
    Page = apps.get_model('knowledge', 'Page')
    
    # Convert all tag pages to regular pages
    Page.objects.filter(page_type="tag").update(page_type="page")


def reverse_tag_pages_conversion(apps, schema_editor):
    """This reverse operation is not meaningful since we're removing the tag concept"""
    # We can't meaningfully reverse this since we're removing the tag page type concept
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0011_remove_page_title_as_tag_alter_page_slug"),
    ]

    operations = [
        migrations.RunPython(
            convert_tag_pages_to_regular,
            reverse_tag_pages_conversion
        ),
    ]
