# Generated by Django 5.0.2 on 2025-07-04 03:15

from django.db import migrations


def migrate_tag_pages_to_regular(apps, schema_editor):
    """Convert any remaining tag pages to regular pages"""
    Page = apps.get_model('knowledge', 'Page')
    
    # Convert all remaining tag pages to regular pages
    updated_count = Page.objects.filter(page_type="tag").update(page_type="page")
    if updated_count > 0:
        print(f"Converted {updated_count} tag pages to regular pages")


def reverse_tag_pages_migration(apps, schema_editor):
    """This reverse operation is not meaningful since we're removing the tag concept"""
    # We can't meaningfully reverse this since we're removing the tag page type concept
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0012_auto_20250704_0308"),
    ]

    operations = [
        migrations.RunPython(
            migrate_tag_pages_to_regular,
            reverse_tag_pages_migration
        ),
    ]
