# Generated by Django 5.0.2 on 2025-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0013_auto_20250704_0315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("page", "Regular Page"),
                    ("daily", "Daily Note"),
                    ("template", "Template"),
                ],
                default="page",
                max_length=20,
            ),
        ),
    ]
