# Generated by Django 5.0.2 on 2025-07-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0014_alter_page_page_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockReference",
        ),
        migrations.DeleteModel(
            name="PageLink",
        ),
    ]
