# Generated by Django 5.0.2 on 2025-07-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0014_alter_page_page_type"),
    ]

    operations = [
        # Drop BlockReference and PageLink tables since they're no longer used
        # These models are replaced by the page/hashtag system
        migrations.RunSQL(
            "DROP TABLE IF EXISTS block_references CASCADE;",
            reverse_sql="-- Cannot reverse dropping block_references table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS page_links CASCADE;",
            reverse_sql="-- Cannot reverse dropping page_links table"
        ),
    ]
