# Generated by Django 5.0.2 on 2025-07-04 04:08

from django.db import migrations


def do_nothing(apps, schema_editor):
    # Models already deleted in migration 0015
    pass


def reverse_do_nothing(apps, schema_editor):
    # No-op reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0015_auto_20250704_0400"),
    ]

    operations = [
        migrations.RunPython(do_nothing, reverse_do_nothing),
    ]
