# Generated by Django 5.0.2 on 2025-07-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0015_auto_20250704_0400"),
    ]

    operations = [
        # These models were already removed from the codebase
        # For safety, we use RunSQL to handle the case where tables might exist
        migrations.RunSQL(
            "DROP TABLE IF EXISTS block_references CASCADE;",
            reverse_sql="-- Cannot reverse dropping block_references table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS page_links CASCADE;",
            reverse_sql="-- Cannot reverse dropping page_links table"
        ),
    ]
