# Generated by Django 5.0.2 on 2025-07-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0016_alter_pagelink_unique_together_and_more"),
    ]

    operations = [
        # Drop the old tagging system tables that were leftover from the previous system
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tagged_items CASCADE;",
            reverse_sql="-- Cannot reverse dropping tagged_items table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tags CASCADE;",
            reverse_sql="-- Cannot reverse dropping tags table"
        ),
    ]
