# Generated by Django 5.0.2 on 2025-07-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0016_alter_pagelink_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("bullet", "Bullet Point"),
                    ("todo", "Todo"),
                    ("done", "Done"),
                    ("later", "Later"),
                    ("wontdo", "Won't Do"),
                    ("heading", "Heading"),
                    ("quote", "Quote"),
                    ("code", "Code Block"),
                    ("divider", "Divider"),
                ],
                default="bullet",
                max_length=20,
            ),
        ),
    ]
