# Generated by Django 5.0.2 on 2025-06-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0002_userproviderconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraisettings",
            name="api_key",
        ),
    ]
