# Generated by Django 5.0.2 on 2025-06-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0003_remove_useraisettings_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraisettings",
            name="provider",
        ),
    ]
