# Generated by Django 5.0.2 on 2025-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0005_add_ai_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproviderconfig",
            name="enabled_models",
        ),
        migrations.AddField(
            model_name="userproviderconfig",
            name="enabled_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Models that this user has enabled for this provider",
                to="ai_chat.aimodel",
            ),
        ),
    ]
