# Generated by Django 5.0.2 on 2025-06-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0006_replace_enabled_models_json_with_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraisettings",
            name="default_model",
        ),
        migrations.AddField(
            model_name="useraisettings",
            name="preferred_model",
            field=models.ForeignKey(
                blank=True,
                help_text="User's preferred AI model for new conversations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_chat.aimodel",
            ),
        ),
    ]
