# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0007_rename_default_to_preferred_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproviderconfig',
            name='encrypted_api_key',
            field=models.TextField(blank=True, help_text='Encrypted API key data'),
        ),
        migrations.AddField(
            model_name='userproviderconfig',
            name='api_key_salt',
            field=models.CharField(blank=True, help_text='Salt for API key encryption', max_length=255),
        ),
        migrations.AddField(
            model_name='userproviderconfig',
            name='api_key_hash',
            field=models.CharField(blank=True, help_text='Hashed API key for verification', max_length=255),
        ),
        migrations.AddField(
            model_name='userproviderconfig',
            name='api_key_hash_salt',
            field=models.CharField(blank=True, help_text='Salt for API key hash', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Legacy plain text field - deprecated', max_length=255),
        ),
        migrations.AddIndex(
            model_name='userproviderconfig',
            index=models.Index(fields=['user', 'provider'], name='ai_chat_use_user_id_ca6c05_idx'),
        ),
        migrations.AddIndex(
            model_name='userproviderconfig',
            index=models.Index(fields=['is_enabled'], name='ai_chat_use_is_enab_b8c42d_idx'),
        ),
    ]