# Generated by Django 5.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_chat', '0008_add_encrypted_api_key_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('accessed', 'Accessed'), ('failed_access', 'Failed Access'), ('encrypted', 'Encrypted'), ('decrypted', 'Decrypted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_chat.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikeyaudit',
            index=models.Index(fields=['user', 'provider'], name='api_key_aud_user_id_a87b56_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyaudit',
            index=models.Index(fields=['operation'], name='api_key_aud_operati_4cc9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyaudit',
            index=models.Index(fields=['created_at'], name='api_key_aud_created_5d8f23_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyaudit',
            index=models.Index(fields=['success'], name='api_key_aud_success_b1e8f9_idx'),
        ),
    ]