# Generated by Django 5.0.2 on 2025-07-03 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0008_drop_websearchconfig_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_chat.aimodel",
            ),
        ),
    ]
