name: Format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      working-directory: ./packages/django-app
      run: just build

    - name: Check Python formatting (Black)
      working-directory: ./packages/django-app
      run: docker-compose run --rm -w /code/app web python -m black . --check --exclude="migrations/"

    - name: Check JavaScript formatting (Prettier)
      working-directory: ./packages/django-app
      run: npx prettier --check .
